# Generated by Django 4.2.7 on 2026-04-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('farmer', 'Farmer'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
