# Generated by Django 4.2.30 on 2026-04-19 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerprofile',
            old_name='bio',
            new_name='description',
        ),
    ]
